name: ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  macos:
    runs-on: macos-12
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-code-coverage --sanitize=thread
    - name: Generate documentation
      uses: sukhrobkhakimov/publish-jazzy-docs@v1
      with:
        personal_access_token: ${{ secrets.ACCESS_TOKEN }}
        args: "--module Yaproq --theme fullwidth --root-url https://yaproq.dev/yaproq --source-host github --source-host-url https://github.com/yaproq/yaproq"
  ubuntu:
    runs-on: ubuntu-latest
    container: swift:5.7-jammy
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-code-coverage --enable-test-discovery --sanitize=thread
    - name: Generate coverage report
      run: llvm-cov export -format="lcov" .build/debug/yaproqPackageTests.xctest -instr-profile=.build/debug/codecov/default.profdata -ignore-filename-regex=".build|Tests" > coverage.lcov
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: base64,unittests
        file: coverage.lcov
